name: 'Hello World'
description: 'Greet someone'
inputs:
  deploy-to:  # id of input
    description: 'what to deploy to'
    required: true
    default: 'jenkins'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo "curl https://localhost"
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # - run: deploy.sh  ${{ inputs.deploy-to }}
    #   shell: bash
